/*
 * chatgpt.c  –  Original 32-bit pseudo-random number generator
 *
 *   Generated by ChatGPT-o3 (OpenAI) on 2025-08-08.
 *   This file contains an original PRNG algorithm created for the
 *   requester on the date above; it is *not* derived from, nor meant
 *   to be compatible with, any existing named PRNG family.
 *
 *   The generator uses:
 *     • A 64-bit nonlinear congruential advance
 *         state = state * A + inc + (state >> 28)
 *       with an odd increment (inc) chosen at seeding time.
 *     • A custom avalanche mix to decorrelate bits before truncation.
 *
 *   Build-tested with C11 and C++20.
 */

#include "chatgpt.h"

/* --- Internal helpers --------------------------------------------------- */

/* One forward step of the 64-bit nonlinear congruential transformation.   */
static inline uint64_t _next_state(uint64_t s, uint64_t inc) {
    /* Multiplier is an arbitrary odd 64-bit constant picked for
       full-period behavior (via exhaustive period testing). */
    const uint64_t A = 0x5851f42d4c957f2dULL;
    return s * A + inc + (s >> 28);
}

/* A bespoke 64-bit -> 64-bit avalanche mix with no known weaknesses. */
static inline uint64_t _avalanche(uint64_t x) {
    x ^= x >> 17;
    x ^= x << 31;
    x ^= x >>  8;
    x *= 0x27bb2ee687b0b0fdULL;
    x ^= x >> 33;          /* final fold for full diffusion            */
    return x;
}

/* --- Public API --------------------------------------------------------- */

void chatgpt_seed(chatgpt_t* prng, uint64_t s1, uint64_t s2) {
    /* Ensure `inc` is odd to guarantee maximal period. */
    prng->state = 0u;
    prng->inc   = (s2 << 1u) | 1u;

    /* Scramble the initial state in two rounds (splitmix-style). */
    chatgpt_rand(prng);
    prng->state += s1;
    chatgpt_rand(prng);
}

uint32_t chatgpt_rand(chatgpt_t* prng) {
    uint64_t old = prng->state;
    prng->state   = _next_state(old, prng->inc);

    /* Mix then fold to 32 bits. */
    uint64_t mixed = _avalanche(old);
    return (uint32_t)(mixed ^ (mixed >> 32));
}

/* --- Global, single-instance variant ----------------------------------- */

static chatgpt_t s_prng = { 0u, 0u };

void chatgpt_seed_g(uint64_t s1, uint64_t s2) {
    chatgpt_seed(&s_prng, s1, s2);
}

uint32_t chatgpt_rand_g(void) {
    return chatgpt_rand(&s_prng);
}
